# name: vanilla-${basename:${dataset.root_dir}}
name: latentgs
tag: ""
seed: 42

dataset:
  name: colmap
  source_path: ???
  model_path: ???
  images: "images"
  resolution: -1
  data_device: "cuda"
  eval: False

model:
  name: vanilla_sg
  pointcloud:
    name: latent_pcd

renderer:
  name: latentgs_renderer
  white_background: False
  debug: False