# name: vanilla-${basename:${dataset.root_dir}}
name: vanilla
tag: ""
seed: 42

dataset:
  name: colmap
  source_path: ???
  model_path: ???
  images: "images"
  resolution: -1
  data_device: "cuda"
  eval: False

model:
  name: vanilla_sg
  pointcloud:
    name: vanilla_pcd
    sh_degree: 3
    resume_path: Null